"""
demo_group_structure.py

Demonstrates group structure computation on two contrasting curves:
  - E1: y^2 = x^3 + x + 1 over F_71   (cyclic group)
  - E2: y^2 = x^3 + x     over F_5    (non-cyclic: Z/2 x Z/2)

Shows how the same curve arithmetic produces qualitatively different
group structures, and verifies the generators by scalar multiplication.
"""
from ecc import PrimeField, Curve, group_order, group_structure, point_order


def print_structure(label, E):
    N = group_order(E)
    (e1, n1), (e2, n2) = group_structure(E)

    print(f"  #E = {N}")
    print(f"  Structure: Z/{n1} x Z/{n2}")
    print(f"  e1 (order {n1}): {e1}")
    if n2 > 1:
        print(f"  e2 (order {n2}): {e2}")
        print(f"  Independent check: [{n1}]*e1 = {E.scalar_mul(n1, e1)}, "
              f"[{n2}]*e2 = {E.scalar_mul(n2, e2)}")
    else:
        print(f"  Group is cyclic — [{n1}]*e1 = {E.scalar_mul(n1, e1)}")


# --- Cyclic example ---
print("E1: y^2 = x^3 + x + 1  over  F_71")
F71 = PrimeField(71)
E1 = Curve(F71, a=1, b=1)
print_structure("E1", E1)
print()

# --- Non-cyclic example: Z/2 x Z/2 ---
print("E2: y^2 = x^3 + x  over  F_5")
F5 = PrimeField(5)
E2 = Curve(F5, a=1, b=0)
print_structure("E2", E2)
print()

# --- Scalar multiplication across the group ---
print("E1 subgroup generated by e1:")
F71 = PrimeField(71)
E1 = Curve(F71, a=1, b=1)
N1 = group_order(E1)
(e1, n1), _ = group_structure(E1)
for k in [1, n1 // 2, n1 - 1, n1]:
    print(f"  [{k}]*e1 = {E1.scalar_mul(k, e1)}")
